#mysql configuration
spring.datasource.url=jdbc:postgresql://dpg-d3ogh624d50c73ep1fjg-a.oregon-postgres.render.com/moneymanager_gxym
spring.datasource.username=moneymanager_gxym_user
spring.datasource.password=pCqOwZuMsXRsEYVe69ZKjmoj4laWMneP



