#mysql configuration
spring.datasource.url=${MYSQL_DB_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

server.servlet.context-path=/api/v1.0

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#email configuration
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username= ${EMAIL_USERNAME}
spring.mail.password= ${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp


#secret key configuration
jwt_secret = ${JWT_SECRET}

money.manager.frontend.url = ${MONEY_MANAGER_FRONTEND_URL}
app.activation.url = ${MONEY_MANAGER_BACKEND_URL}

spring.profiles.active=prod