#mysql configuration
spring.datasource.url= ${POSTGRES_DB_URL_RENDER}
spring.datasource.username=${POSTGRES_USERNAME_RENDER}
spring.datasource.password=${POSTGRES_PASSWORD_RENDER}
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false